
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const UserStatus = {
  PENDING_PROFILE: 'PENDING_PROFILE',
  PROCESSING: 'PROCESSING',
  READY: 'READY'
} as const

export type UserStatus = (typeof UserStatus)[keyof typeof UserStatus]


export const AiJobType = {
  SUMMARY: 'SUMMARY'
} as const

export type AiJobType = (typeof AiJobType)[keyof typeof AiJobType]


export const AiJobStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type AiJobStatus = (typeof AiJobStatus)[keyof typeof AiJobStatus]
