
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AiSummary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AiSummary
 * 
 */
export type AiSummaryModel = runtime.Types.Result.DefaultSelection<Prisma.$AiSummaryPayload>

export type AggregateAiSummary = {
  _count: AiSummaryCountAggregateOutputType | null
  _min: AiSummaryMinAggregateOutputType | null
  _max: AiSummaryMaxAggregateOutputType | null
}

export type AiSummaryMinAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  summary: string | null
  generatedAt: Date | null
}

export type AiSummaryMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  title: string | null
  summary: string | null
  generatedAt: Date | null
}

export type AiSummaryCountAggregateOutputType = {
  id: number
  userId: number
  title: number
  summary: number
  strengths: number
  recommendations: number
  generatedAt: number
  _all: number
}


export type AiSummaryMinAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  summary?: true
  generatedAt?: true
}

export type AiSummaryMaxAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  summary?: true
  generatedAt?: true
}

export type AiSummaryCountAggregateInputType = {
  id?: true
  userId?: true
  title?: true
  summary?: true
  strengths?: true
  recommendations?: true
  generatedAt?: true
  _all?: true
}

export type AiSummaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AiSummary to aggregate.
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiSummaries to fetch.
   */
  orderBy?: Prisma.AiSummaryOrderByWithRelationInput | Prisma.AiSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AiSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AiSummaries
  **/
  _count?: true | AiSummaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AiSummaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AiSummaryMaxAggregateInputType
}

export type GetAiSummaryAggregateType<T extends AiSummaryAggregateArgs> = {
      [P in keyof T & keyof AggregateAiSummary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAiSummary[P]>
    : Prisma.GetScalarType<T[P], AggregateAiSummary[P]>
}




export type AiSummaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AiSummaryWhereInput
  orderBy?: Prisma.AiSummaryOrderByWithAggregationInput | Prisma.AiSummaryOrderByWithAggregationInput[]
  by: Prisma.AiSummaryScalarFieldEnum[] | Prisma.AiSummaryScalarFieldEnum
  having?: Prisma.AiSummaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AiSummaryCountAggregateInputType | true
  _min?: AiSummaryMinAggregateInputType
  _max?: AiSummaryMaxAggregateInputType
}

export type AiSummaryGroupByOutputType = {
  id: string
  userId: string
  title: string
  summary: string
  strengths: string[]
  recommendations: string[]
  generatedAt: Date
  _count: AiSummaryCountAggregateOutputType | null
  _min: AiSummaryMinAggregateOutputType | null
  _max: AiSummaryMaxAggregateOutputType | null
}

type GetAiSummaryGroupByPayload<T extends AiSummaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AiSummaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AiSummaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AiSummaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AiSummaryGroupByOutputType[P]>
      }
    >
  >



export type AiSummaryWhereInput = {
  AND?: Prisma.AiSummaryWhereInput | Prisma.AiSummaryWhereInput[]
  OR?: Prisma.AiSummaryWhereInput[]
  NOT?: Prisma.AiSummaryWhereInput | Prisma.AiSummaryWhereInput[]
  id?: Prisma.StringFilter<"AiSummary"> | string
  userId?: Prisma.StringFilter<"AiSummary"> | string
  title?: Prisma.StringFilter<"AiSummary"> | string
  summary?: Prisma.StringFilter<"AiSummary"> | string
  strengths?: Prisma.StringNullableListFilter<"AiSummary">
  recommendations?: Prisma.StringNullableListFilter<"AiSummary">
  generatedAt?: Prisma.DateTimeFilter<"AiSummary"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AiSummaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  strengths?: Prisma.SortOrder
  recommendations?: Prisma.SortOrder
  generatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AiSummaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.AiSummaryWhereInput | Prisma.AiSummaryWhereInput[]
  OR?: Prisma.AiSummaryWhereInput[]
  NOT?: Prisma.AiSummaryWhereInput | Prisma.AiSummaryWhereInput[]
  title?: Prisma.StringFilter<"AiSummary"> | string
  summary?: Prisma.StringFilter<"AiSummary"> | string
  strengths?: Prisma.StringNullableListFilter<"AiSummary">
  recommendations?: Prisma.StringNullableListFilter<"AiSummary">
  generatedAt?: Prisma.DateTimeFilter<"AiSummary"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type AiSummaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  strengths?: Prisma.SortOrder
  recommendations?: Prisma.SortOrder
  generatedAt?: Prisma.SortOrder
  _count?: Prisma.AiSummaryCountOrderByAggregateInput
  _max?: Prisma.AiSummaryMaxOrderByAggregateInput
  _min?: Prisma.AiSummaryMinOrderByAggregateInput
}

export type AiSummaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.AiSummaryScalarWhereWithAggregatesInput | Prisma.AiSummaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.AiSummaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AiSummaryScalarWhereWithAggregatesInput | Prisma.AiSummaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AiSummary"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AiSummary"> | string
  title?: Prisma.StringWithAggregatesFilter<"AiSummary"> | string
  summary?: Prisma.StringWithAggregatesFilter<"AiSummary"> | string
  strengths?: Prisma.StringNullableListFilter<"AiSummary">
  recommendations?: Prisma.StringNullableListFilter<"AiSummary">
  generatedAt?: Prisma.DateTimeWithAggregatesFilter<"AiSummary"> | Date | string
}

export type AiSummaryCreateInput = {
  id?: string
  title: string
  summary: string
  strengths?: Prisma.AiSummaryCreatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryCreaterecommendationsInput | string[]
  generatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAiSummaryInput
}

export type AiSummaryUncheckedCreateInput = {
  id?: string
  userId: string
  title: string
  summary: string
  strengths?: Prisma.AiSummaryCreatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryCreaterecommendationsInput | string[]
  generatedAt?: Date | string
}

export type AiSummaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAiSummaryNestedInput
}

export type AiSummaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiSummaryCreateManyInput = {
  id?: string
  userId: string
  title: string
  summary: string
  strengths?: Prisma.AiSummaryCreatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryCreaterecommendationsInput | string[]
  generatedAt?: Date | string
}

export type AiSummaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiSummaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiSummaryNullableScalarRelationFilter = {
  is?: Prisma.AiSummaryWhereInput | null
  isNot?: Prisma.AiSummaryWhereInput | null
}

export type AiSummaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  strengths?: Prisma.SortOrder
  recommendations?: Prisma.SortOrder
  generatedAt?: Prisma.SortOrder
}

export type AiSummaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  generatedAt?: Prisma.SortOrder
}

export type AiSummaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  title?: Prisma.SortOrder
  summary?: Prisma.SortOrder
  generatedAt?: Prisma.SortOrder
}

export type AiSummaryCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AiSummaryCreateOrConnectWithoutUserInput
  connect?: Prisma.AiSummaryWhereUniqueInput
}

export type AiSummaryUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AiSummaryCreateOrConnectWithoutUserInput
  connect?: Prisma.AiSummaryWhereUniqueInput
}

export type AiSummaryUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AiSummaryCreateOrConnectWithoutUserInput
  upsert?: Prisma.AiSummaryUpsertWithoutUserInput
  disconnect?: Prisma.AiSummaryWhereInput | boolean
  delete?: Prisma.AiSummaryWhereInput | boolean
  connect?: Prisma.AiSummaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AiSummaryUpdateToOneWithWhereWithoutUserInput, Prisma.AiSummaryUpdateWithoutUserInput>, Prisma.AiSummaryUncheckedUpdateWithoutUserInput>
}

export type AiSummaryUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.AiSummaryCreateOrConnectWithoutUserInput
  upsert?: Prisma.AiSummaryUpsertWithoutUserInput
  disconnect?: Prisma.AiSummaryWhereInput | boolean
  delete?: Prisma.AiSummaryWhereInput | boolean
  connect?: Prisma.AiSummaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AiSummaryUpdateToOneWithWhereWithoutUserInput, Prisma.AiSummaryUpdateWithoutUserInput>, Prisma.AiSummaryUncheckedUpdateWithoutUserInput>
}

export type AiSummaryCreatestrengthsInput = {
  set: string[]
}

export type AiSummaryCreaterecommendationsInput = {
  set: string[]
}

export type AiSummaryUpdatestrengthsInput = {
  set?: string[]
  push?: string | string[]
}

export type AiSummaryUpdaterecommendationsInput = {
  set?: string[]
  push?: string | string[]
}

export type AiSummaryCreateWithoutUserInput = {
  id?: string
  title: string
  summary: string
  strengths?: Prisma.AiSummaryCreatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryCreaterecommendationsInput | string[]
  generatedAt?: Date | string
}

export type AiSummaryUncheckedCreateWithoutUserInput = {
  id?: string
  title: string
  summary: string
  strengths?: Prisma.AiSummaryCreatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryCreaterecommendationsInput | string[]
  generatedAt?: Date | string
}

export type AiSummaryCreateOrConnectWithoutUserInput = {
  where: Prisma.AiSummaryWhereUniqueInput
  create: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
}

export type AiSummaryUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.AiSummaryUpdateWithoutUserInput, Prisma.AiSummaryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AiSummaryCreateWithoutUserInput, Prisma.AiSummaryUncheckedCreateWithoutUserInput>
  where?: Prisma.AiSummaryWhereInput
}

export type AiSummaryUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.AiSummaryWhereInput
  data: Prisma.XOR<Prisma.AiSummaryUpdateWithoutUserInput, Prisma.AiSummaryUncheckedUpdateWithoutUserInput>
}

export type AiSummaryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AiSummaryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  summary?: Prisma.StringFieldUpdateOperationsInput | string
  strengths?: Prisma.AiSummaryUpdatestrengthsInput | string[]
  recommendations?: Prisma.AiSummaryUpdaterecommendationsInput | string[]
  generatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AiSummarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  summary?: boolean
  strengths?: boolean
  recommendations?: boolean
  generatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiSummary"]>

export type AiSummarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  summary?: boolean
  strengths?: boolean
  recommendations?: boolean
  generatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiSummary"]>

export type AiSummarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  title?: boolean
  summary?: boolean
  strengths?: boolean
  recommendations?: boolean
  generatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["aiSummary"]>

export type AiSummarySelectScalar = {
  id?: boolean
  userId?: boolean
  title?: boolean
  summary?: boolean
  strengths?: boolean
  recommendations?: boolean
  generatedAt?: boolean
}

export type AiSummaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "title" | "summary" | "strengths" | "recommendations" | "generatedAt", ExtArgs["result"]["aiSummary"]>
export type AiSummaryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AiSummaryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AiSummaryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AiSummaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AiSummary"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    title: string
    summary: string
    strengths: string[]
    recommendations: string[]
    generatedAt: Date
  }, ExtArgs["result"]["aiSummary"]>
  composites: {}
}

export type AiSummaryGetPayload<S extends boolean | null | undefined | AiSummaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload, S>

export type AiSummaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AiSummaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AiSummaryCountAggregateInputType | true
  }

export interface AiSummaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AiSummary'], meta: { name: 'AiSummary' } }
  /**
   * Find zero or one AiSummary that matches the filter.
   * @param {AiSummaryFindUniqueArgs} args - Arguments to find a AiSummary
   * @example
   * // Get one AiSummary
   * const aiSummary = await prisma.aiSummary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AiSummaryFindUniqueArgs>(args: Prisma.SelectSubset<T, AiSummaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AiSummary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AiSummaryFindUniqueOrThrowArgs} args - Arguments to find a AiSummary
   * @example
   * // Get one AiSummary
   * const aiSummary = await prisma.aiSummary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AiSummaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AiSummaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AiSummary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryFindFirstArgs} args - Arguments to find a AiSummary
   * @example
   * // Get one AiSummary
   * const aiSummary = await prisma.aiSummary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AiSummaryFindFirstArgs>(args?: Prisma.SelectSubset<T, AiSummaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AiSummary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryFindFirstOrThrowArgs} args - Arguments to find a AiSummary
   * @example
   * // Get one AiSummary
   * const aiSummary = await prisma.aiSummary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AiSummaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AiSummaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AiSummaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AiSummaries
   * const aiSummaries = await prisma.aiSummary.findMany()
   * 
   * // Get first 10 AiSummaries
   * const aiSummaries = await prisma.aiSummary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const aiSummaryWithIdOnly = await prisma.aiSummary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AiSummaryFindManyArgs>(args?: Prisma.SelectSubset<T, AiSummaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AiSummary.
   * @param {AiSummaryCreateArgs} args - Arguments to create a AiSummary.
   * @example
   * // Create one AiSummary
   * const AiSummary = await prisma.aiSummary.create({
   *   data: {
   *     // ... data to create a AiSummary
   *   }
   * })
   * 
   */
  create<T extends AiSummaryCreateArgs>(args: Prisma.SelectSubset<T, AiSummaryCreateArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AiSummaries.
   * @param {AiSummaryCreateManyArgs} args - Arguments to create many AiSummaries.
   * @example
   * // Create many AiSummaries
   * const aiSummary = await prisma.aiSummary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AiSummaryCreateManyArgs>(args?: Prisma.SelectSubset<T, AiSummaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AiSummaries and returns the data saved in the database.
   * @param {AiSummaryCreateManyAndReturnArgs} args - Arguments to create many AiSummaries.
   * @example
   * // Create many AiSummaries
   * const aiSummary = await prisma.aiSummary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AiSummaries and only return the `id`
   * const aiSummaryWithIdOnly = await prisma.aiSummary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AiSummaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AiSummaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AiSummary.
   * @param {AiSummaryDeleteArgs} args - Arguments to delete one AiSummary.
   * @example
   * // Delete one AiSummary
   * const AiSummary = await prisma.aiSummary.delete({
   *   where: {
   *     // ... filter to delete one AiSummary
   *   }
   * })
   * 
   */
  delete<T extends AiSummaryDeleteArgs>(args: Prisma.SelectSubset<T, AiSummaryDeleteArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AiSummary.
   * @param {AiSummaryUpdateArgs} args - Arguments to update one AiSummary.
   * @example
   * // Update one AiSummary
   * const aiSummary = await prisma.aiSummary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AiSummaryUpdateArgs>(args: Prisma.SelectSubset<T, AiSummaryUpdateArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AiSummaries.
   * @param {AiSummaryDeleteManyArgs} args - Arguments to filter AiSummaries to delete.
   * @example
   * // Delete a few AiSummaries
   * const { count } = await prisma.aiSummary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AiSummaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, AiSummaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AiSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AiSummaries
   * const aiSummary = await prisma.aiSummary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AiSummaryUpdateManyArgs>(args: Prisma.SelectSubset<T, AiSummaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AiSummaries and returns the data updated in the database.
   * @param {AiSummaryUpdateManyAndReturnArgs} args - Arguments to update many AiSummaries.
   * @example
   * // Update many AiSummaries
   * const aiSummary = await prisma.aiSummary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AiSummaries and only return the `id`
   * const aiSummaryWithIdOnly = await prisma.aiSummary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AiSummaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AiSummaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AiSummary.
   * @param {AiSummaryUpsertArgs} args - Arguments to update or create a AiSummary.
   * @example
   * // Update or create a AiSummary
   * const aiSummary = await prisma.aiSummary.upsert({
   *   create: {
   *     // ... data to create a AiSummary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AiSummary we want to update
   *   }
   * })
   */
  upsert<T extends AiSummaryUpsertArgs>(args: Prisma.SelectSubset<T, AiSummaryUpsertArgs<ExtArgs>>): Prisma.Prisma__AiSummaryClient<runtime.Types.Result.GetResult<Prisma.$AiSummaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AiSummaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryCountArgs} args - Arguments to filter AiSummaries to count.
   * @example
   * // Count the number of AiSummaries
   * const count = await prisma.aiSummary.count({
   *   where: {
   *     // ... the filter for the AiSummaries we want to count
   *   }
   * })
  **/
  count<T extends AiSummaryCountArgs>(
    args?: Prisma.Subset<T, AiSummaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AiSummaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AiSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AiSummaryAggregateArgs>(args: Prisma.Subset<T, AiSummaryAggregateArgs>): Prisma.PrismaPromise<GetAiSummaryAggregateType<T>>

  /**
   * Group by AiSummary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AiSummaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AiSummaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AiSummaryGroupByArgs['orderBy'] }
      : { orderBy?: AiSummaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AiSummaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAiSummaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AiSummary model
 */
readonly fields: AiSummaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AiSummary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AiSummaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AiSummary model
 */
export interface AiSummaryFieldRefs {
  readonly id: Prisma.FieldRef<"AiSummary", 'String'>
  readonly userId: Prisma.FieldRef<"AiSummary", 'String'>
  readonly title: Prisma.FieldRef<"AiSummary", 'String'>
  readonly summary: Prisma.FieldRef<"AiSummary", 'String'>
  readonly strengths: Prisma.FieldRef<"AiSummary", 'String[]'>
  readonly recommendations: Prisma.FieldRef<"AiSummary", 'String[]'>
  readonly generatedAt: Prisma.FieldRef<"AiSummary", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AiSummary findUnique
 */
export type AiSummaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter, which AiSummary to fetch.
   */
  where: Prisma.AiSummaryWhereUniqueInput
}

/**
 * AiSummary findUniqueOrThrow
 */
export type AiSummaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter, which AiSummary to fetch.
   */
  where: Prisma.AiSummaryWhereUniqueInput
}

/**
 * AiSummary findFirst
 */
export type AiSummaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter, which AiSummary to fetch.
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiSummaries to fetch.
   */
  orderBy?: Prisma.AiSummaryOrderByWithRelationInput | Prisma.AiSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AiSummaries.
   */
  cursor?: Prisma.AiSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AiSummaries.
   */
  distinct?: Prisma.AiSummaryScalarFieldEnum | Prisma.AiSummaryScalarFieldEnum[]
}

/**
 * AiSummary findFirstOrThrow
 */
export type AiSummaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter, which AiSummary to fetch.
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiSummaries to fetch.
   */
  orderBy?: Prisma.AiSummaryOrderByWithRelationInput | Prisma.AiSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AiSummaries.
   */
  cursor?: Prisma.AiSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiSummaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AiSummaries.
   */
  distinct?: Prisma.AiSummaryScalarFieldEnum | Prisma.AiSummaryScalarFieldEnum[]
}

/**
 * AiSummary findMany
 */
export type AiSummaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter, which AiSummaries to fetch.
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AiSummaries to fetch.
   */
  orderBy?: Prisma.AiSummaryOrderByWithRelationInput | Prisma.AiSummaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AiSummaries.
   */
  cursor?: Prisma.AiSummaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AiSummaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AiSummaries.
   */
  skip?: number
  distinct?: Prisma.AiSummaryScalarFieldEnum | Prisma.AiSummaryScalarFieldEnum[]
}

/**
 * AiSummary create
 */
export type AiSummaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * The data needed to create a AiSummary.
   */
  data: Prisma.XOR<Prisma.AiSummaryCreateInput, Prisma.AiSummaryUncheckedCreateInput>
}

/**
 * AiSummary createMany
 */
export type AiSummaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AiSummaries.
   */
  data: Prisma.AiSummaryCreateManyInput | Prisma.AiSummaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AiSummary createManyAndReturn
 */
export type AiSummaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * The data used to create many AiSummaries.
   */
  data: Prisma.AiSummaryCreateManyInput | Prisma.AiSummaryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AiSummary update
 */
export type AiSummaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * The data needed to update a AiSummary.
   */
  data: Prisma.XOR<Prisma.AiSummaryUpdateInput, Prisma.AiSummaryUncheckedUpdateInput>
  /**
   * Choose, which AiSummary to update.
   */
  where: Prisma.AiSummaryWhereUniqueInput
}

/**
 * AiSummary updateMany
 */
export type AiSummaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AiSummaries.
   */
  data: Prisma.XOR<Prisma.AiSummaryUpdateManyMutationInput, Prisma.AiSummaryUncheckedUpdateManyInput>
  /**
   * Filter which AiSummaries to update
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * Limit how many AiSummaries to update.
   */
  limit?: number
}

/**
 * AiSummary updateManyAndReturn
 */
export type AiSummaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * The data used to update AiSummaries.
   */
  data: Prisma.XOR<Prisma.AiSummaryUpdateManyMutationInput, Prisma.AiSummaryUncheckedUpdateManyInput>
  /**
   * Filter which AiSummaries to update
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * Limit how many AiSummaries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AiSummary upsert
 */
export type AiSummaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * The filter to search for the AiSummary to update in case it exists.
   */
  where: Prisma.AiSummaryWhereUniqueInput
  /**
   * In case the AiSummary found by the `where` argument doesn't exist, create a new AiSummary with this data.
   */
  create: Prisma.XOR<Prisma.AiSummaryCreateInput, Prisma.AiSummaryUncheckedCreateInput>
  /**
   * In case the AiSummary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AiSummaryUpdateInput, Prisma.AiSummaryUncheckedUpdateInput>
}

/**
 * AiSummary delete
 */
export type AiSummaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
  /**
   * Filter which AiSummary to delete.
   */
  where: Prisma.AiSummaryWhereUniqueInput
}

/**
 * AiSummary deleteMany
 */
export type AiSummaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AiSummaries to delete
   */
  where?: Prisma.AiSummaryWhereInput
  /**
   * Limit how many AiSummaries to delete.
   */
  limit?: number
}

/**
 * AiSummary without action
 */
export type AiSummaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AiSummary
   */
  select?: Prisma.AiSummarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the AiSummary
   */
  omit?: Prisma.AiSummaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AiSummaryInclude<ExtArgs> | null
}
